In [1]:
import numpy as np

In [9]:
theta = np.array([0.5,1,2])
X = np.random.rand(5,3)

In [10]:
X

array([[0.59714913, 0.1723671 , 0.81549265],
       [0.8880605 , 0.53977009, 0.51177772],
       [0.11109718, 0.65408254, 0.24973243],
       [0.88204453, 0.80596048, 0.41116998],
       [0.77501215, 0.07104707, 0.07242317]])

In [23]:
X.dot(theta)

array([2.10192696, 2.00735578, 1.20909599, 2.06932271, 0.60339948])

In [27]:
theta.dot(X.T)

array([2.10192696, 2.00735578, 1.20909599, 2.06932271, 0.60339948])

In [28]:
np.matmul(X,theta)

array([2.10192696, 2.00735578, 1.20909599, 2.06932271, 0.60339948])